### PR TITLE
Updated Icon & added category images

### PR DESCRIPTION
**Pull request by icpryde**
This is a better version of the previous icon, higher quality and larger size 512x512. I also created a new folder to put the images for the categories inside.

### CODE REVIEW

**Comment by icpryde** [comment]
I don't know how to add to the actual code to add the category images to the appropriate places so someone will need to do that part.

**Comment by DxCx** [comment]
what updates the menu?
can you upload a screenshot of how it looks in kodi please?

**Comment by icpryde** [comment]
@DxCx So I don't currently have it on Kodi because I don't know how to do the coding part which is why I only uploading the images. This is what I was wanting it to look like on the Kodi Add-on.



This is what it currently looks like with the add-on.



This is to get rid of the generic folder icons and just make the add-on look nicer.

**Comment by ItachiSharingan** [comment]
that kinda seems unnecessary since it just repeats what the title label says

**Comment by icpryde** [comment]
It’s not about “necessary” I already did the hard part myself. It’s about making it look cleaner.

**Comment by ItachiSharingan** [comment]
it doesn't make it cleaner since it just repeats the title.

**Comment by icpryde** [comment]
@DxCx I don’t currently have it on kodi addon because I don’t know how to code but right now when you go into the addon and see all the categories the spot where an image would go is just showing a blank generic folder icon. These images would replace the generic icon.

I’ll give you an example with an addon called today, see the red image for the movie category? These images would effectively do the same thing.
83EE0043-8837-4C40-9D7E-2FB230D4AE80

**Comment by icpryde** [comment]
Ok then just update the main icon and don't use the category icons.

**Comment by SasukeShiro** [comment]
@icpryde do you have white background version of icon image, it looks cleaner imo

**Comment by icpryde** [comment]
I made both white icon and orange icon and I feel the orange fits the website theme better but also it’s easier on the eyes as white in the dark is very bright.

**Comment by icpryde** [comment]
@DxCx so I deleted all the category images, guess people don’t want that. I left the icon to be changed though with a higher quality one.

**Pull request closed without merging**
